// Copyright JAMF Software, LLC

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v5.29.3
// source: maintenance.proto

package regattapb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// BackupRequest requests and opens a stream with backup data.
type BackupRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// table is name of the table to stream.
	Table         []byte `protobuf:"bytes,1,opt,name=table,proto3" json:"table,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BackupRequest) Reset() {
	*x = BackupRequest{}
	mi := &file_maintenance_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BackupRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BackupRequest) ProtoMessage() {}

func (x *BackupRequest) ProtoReflect() protoreflect.Message {
	mi := &file_maintenance_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BackupRequest.ProtoReflect.Descriptor instead.
func (*BackupRequest) Descriptor() ([]byte, []int) {
	return file_maintenance_proto_rawDescGZIP(), []int{0}
}

func (x *BackupRequest) GetTable() []byte {
	if x != nil {
		return x.Table
	}
	return nil
}

// RestoreMessage contains either info of the table being restored or chunk of a backup data.
type RestoreMessage struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Data:
	//
	//	*RestoreMessage_Info
	//	*RestoreMessage_Chunk
	Data          isRestoreMessage_Data `protobuf_oneof:"data"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RestoreMessage) Reset() {
	*x = RestoreMessage{}
	mi := &file_maintenance_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RestoreMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RestoreMessage) ProtoMessage() {}

func (x *RestoreMessage) ProtoReflect() protoreflect.Message {
	mi := &file_maintenance_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RestoreMessage.ProtoReflect.Descriptor instead.
func (*RestoreMessage) Descriptor() ([]byte, []int) {
	return file_maintenance_proto_rawDescGZIP(), []int{1}
}

func (x *RestoreMessage) GetData() isRestoreMessage_Data {
	if x != nil {
		return x.Data
	}
	return nil
}

func (x *RestoreMessage) GetInfo() *RestoreInfo {
	if x != nil {
		if x, ok := x.Data.(*RestoreMessage_Info); ok {
			return x.Info
		}
	}
	return nil
}

func (x *RestoreMessage) GetChunk() *SnapshotChunk {
	if x != nil {
		if x, ok := x.Data.(*RestoreMessage_Chunk); ok {
			return x.Chunk
		}
	}
	return nil
}

type isRestoreMessage_Data interface {
	isRestoreMessage_Data()
}

type RestoreMessage_Info struct {
	Info *RestoreInfo `protobuf:"bytes,1,opt,name=info,proto3,oneof"`
}

type RestoreMessage_Chunk struct {
	Chunk *SnapshotChunk `protobuf:"bytes,2,opt,name=chunk,proto3,oneof"`
}

func (*RestoreMessage_Info) isRestoreMessage_Data() {}

func (*RestoreMessage_Chunk) isRestoreMessage_Data() {}

// RestoreInfo metadata of restore snapshot that is going to be uploaded.
type RestoreInfo struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// table is name of the table in the stream.
	Table         []byte `protobuf:"bytes,1,opt,name=table,proto3" json:"table,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RestoreInfo) Reset() {
	*x = RestoreInfo{}
	mi := &file_maintenance_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RestoreInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RestoreInfo) ProtoMessage() {}

func (x *RestoreInfo) ProtoReflect() protoreflect.Message {
	mi := &file_maintenance_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RestoreInfo.ProtoReflect.Descriptor instead.
func (*RestoreInfo) Descriptor() ([]byte, []int) {
	return file_maintenance_proto_rawDescGZIP(), []int{2}
}

func (x *RestoreInfo) GetTable() []byte {
	if x != nil {
		return x.Table
	}
	return nil
}

type RestoreResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RestoreResponse) Reset() {
	*x = RestoreResponse{}
	mi := &file_maintenance_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RestoreResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RestoreResponse) ProtoMessage() {}

func (x *RestoreResponse) ProtoReflect() protoreflect.Message {
	mi := &file_maintenance_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RestoreResponse.ProtoReflect.Descriptor instead.
func (*RestoreResponse) Descriptor() ([]byte, []int) {
	return file_maintenance_proto_rawDescGZIP(), []int{3}
}

// ResetRequest resets either a single or multiple tables in the cluster, meaning that their data will be repopulated from the Leader.
type ResetRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// table is a table name to reset.
	Table []byte `protobuf:"bytes,1,opt,name=table,proto3" json:"table,omitempty"`
	// reset_all if true all the tables will be reset, use with caution.
	ResetAll      bool `protobuf:"varint,2,opt,name=reset_all,json=resetAll,proto3" json:"reset_all,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ResetRequest) Reset() {
	*x = ResetRequest{}
	mi := &file_maintenance_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ResetRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResetRequest) ProtoMessage() {}

func (x *ResetRequest) ProtoReflect() protoreflect.Message {
	mi := &file_maintenance_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResetRequest.ProtoReflect.Descriptor instead.
func (*ResetRequest) Descriptor() ([]byte, []int) {
	return file_maintenance_proto_rawDescGZIP(), []int{4}
}

func (x *ResetRequest) GetTable() []byte {
	if x != nil {
		return x.Table
	}
	return nil
}

func (x *ResetRequest) GetResetAll() bool {
	if x != nil {
		return x.ResetAll
	}
	return false
}

type ResetResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ResetResponse) Reset() {
	*x = ResetResponse{}
	mi := &file_maintenance_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ResetResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResetResponse) ProtoMessage() {}

func (x *ResetResponse) ProtoReflect() protoreflect.Message {
	mi := &file_maintenance_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResetResponse.ProtoReflect.Descriptor instead.
func (*ResetResponse) Descriptor() ([]byte, []int) {
	return file_maintenance_proto_rawDescGZIP(), []int{5}
}

var File_maintenance_proto protoreflect.FileDescriptor

const file_maintenance_proto_rawDesc = "" +
	"\n" +
	"\x11maintenance.proto\x12\x0emaintenance.v1\x1a\x11replication.proto\"%\n" +
	"\rBackupRequest\x12\x14\n" +
	"\x05table\x18\x01 \x01(\fR\x05table\"\x82\x01\n" +
	"\x0eRestoreMessage\x121\n" +
	"\x04info\x18\x01 \x01(\v2\x1b.maintenance.v1.RestoreInfoH\x00R\x04info\x125\n" +
	"\x05chunk\x18\x02 \x01(\v2\x1d.replication.v1.SnapshotChunkH\x00R\x05chunkB\x06\n" +
	"\x04data\"#\n" +
	"\vRestoreInfo\x12\x14\n" +
	"\x05table\x18\x01 \x01(\fR\x05table\"\x11\n" +
	"\x0fRestoreResponse\"A\n" +
	"\fResetRequest\x12\x14\n" +
	"\x05table\x18\x01 \x01(\fR\x05table\x12\x1b\n" +
	"\treset_all\x18\x02 \x01(\bR\bresetAll\"\x0f\n" +
	"\rResetResponse2\xeb\x01\n" +
	"\vMaintenance\x12H\n" +
	"\x06Backup\x12\x1d.maintenance.v1.BackupRequest\x1a\x1d.replication.v1.SnapshotChunk0\x01\x12L\n" +
	"\aRestore\x12\x1e.maintenance.v1.RestoreMessage\x1a\x1f.maintenance.v1.RestoreResponse(\x01\x12D\n" +
	"\x05Reset\x12\x1c.maintenance.v1.ResetRequest\x1a\x1d.maintenance.v1.ResetResponseB\rZ\v./regattapbb\x06proto3"

var (
	file_maintenance_proto_rawDescOnce sync.Once
	file_maintenance_proto_rawDescData []byte
)

func file_maintenance_proto_rawDescGZIP() []byte {
	file_maintenance_proto_rawDescOnce.Do(func() {
		file_maintenance_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_maintenance_proto_rawDesc), len(file_maintenance_proto_rawDesc)))
	})
	return file_maintenance_proto_rawDescData
}

var file_maintenance_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_maintenance_proto_goTypes = []any{
	(*BackupRequest)(nil),   // 0: maintenance.v1.BackupRequest
	(*RestoreMessage)(nil),  // 1: maintenance.v1.RestoreMessage
	(*RestoreInfo)(nil),     // 2: maintenance.v1.RestoreInfo
	(*RestoreResponse)(nil), // 3: maintenance.v1.RestoreResponse
	(*ResetRequest)(nil),    // 4: maintenance.v1.ResetRequest
	(*ResetResponse)(nil),   // 5: maintenance.v1.ResetResponse
	(*SnapshotChunk)(nil),   // 6: replication.v1.SnapshotChunk
}
var file_maintenance_proto_depIdxs = []int32{
	2, // 0: maintenance.v1.RestoreMessage.info:type_name -> maintenance.v1.RestoreInfo
	6, // 1: maintenance.v1.RestoreMessage.chunk:type_name -> replication.v1.SnapshotChunk
	0, // 2: maintenance.v1.Maintenance.Backup:input_type -> maintenance.v1.BackupRequest
	1, // 3: maintenance.v1.Maintenance.Restore:input_type -> maintenance.v1.RestoreMessage
	4, // 4: maintenance.v1.Maintenance.Reset:input_type -> maintenance.v1.ResetRequest
	6, // 5: maintenance.v1.Maintenance.Backup:output_type -> replication.v1.SnapshotChunk
	3, // 6: maintenance.v1.Maintenance.Restore:output_type -> maintenance.v1.RestoreResponse
	5, // 7: maintenance.v1.Maintenance.Reset:output_type -> maintenance.v1.ResetResponse
	5, // [5:8] is the sub-list for method output_type
	2, // [2:5] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_maintenance_proto_init() }
func file_maintenance_proto_init() {
	if File_maintenance_proto != nil {
		return
	}
	file_replication_proto_init()
	file_maintenance_proto_msgTypes[1].OneofWrappers = []any{
		(*RestoreMessage_Info)(nil),
		(*RestoreMessage_Chunk)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_maintenance_proto_rawDesc), len(file_maintenance_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_maintenance_proto_goTypes,
		DependencyIndexes: file_maintenance_proto_depIdxs,
		MessageInfos:      file_maintenance_proto_msgTypes,
	}.Build()
	File_maintenance_proto = out.File
	file_maintenance_proto_goTypes = nil
	file_maintenance_proto_depIdxs = nil
}
